'use client';

import { useCallback, useEffect, useState } from 'react';
import './merchant.css';

const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL ?? 'http://localhost:4000';
type MerchantDemo = { merchant: { name: string; city: string; status: string }; metrics: { paid_count: number; paid_volume_khr: string; active_vouchers: number; loyalty_members: number }; customer: { id: string; name: string | null; points_balance: number; tier: string; wallet_url: string }; payments: { id: string; amount: string; currency: string; reference: string | null; paid_at: string; receipt_url: string }[] };

export default function MerchantDemoPage() {
  const [data, setData] = useState<MerchantDemo | null>(null);
  const [error, setError] = useState('');
  const load = useCallback(async () => { try { setError(''); const r = await fetch(`${API_BASE}/demo/mobile/merchant`, { cache: 'no-store' }); if (!r.ok) throw new Error(); setData(await r.json()); } catch { setError('The demo merchant data is unavailable.'); } }, []);
  useEffect(() => { load(); }, [load]);
  if (!data) return <main className="merchant-demo"><section className="merchant-board loading-board"><b>◆ PayKH merchant demo</b><h1>{error || 'Loading the demo merchant…'}</h1><button onClick={load}>Retry</button></section></main>;
  const latest = data.payments[0];
  return <main className="merchant-demo"><section className="merchant-board"><header><div className="merchant-brand"><i>◆</i><b>PayKH</b><span>Merchant demo</span></div><button onClick={load}>↻ Refresh</button></header><div className="merchant-title"><div><p>TEST MODE · LIVE DEMO DATA</p><h1>{data.merchant.name}</h1><span>{data.merchant.city} · KHQR enabled</span></div><a href="/wallet">Open mobile demo →</a></div><section className="metric-grid"><Metric icon="៛" label="Demo payment volume" value={`៛ ${Number(data.metrics.paid_volume_khr).toLocaleString()}`} detail={`${data.metrics.paid_count} confirmed payment${data.metrics.paid_count === 1 ? '' : 's'}`} /><Metric icon="✦" label="Loyalty member" value={data.customer.name ?? 'Demo customer'} detail={`${data.customer.points_balance.toLocaleString()} points · ${data.customer.tier}`} /><Metric icon="✓" label="Vouchers ready" value={`${data.metrics.active_vouchers}`} detail="Reward redemptions to fulfil" /></section><section className="merchant-grid"><article className="payment-card"><div className="section-label">LATEST KHQR PAYMENT</div>{latest ? <><div className="payment-head"><span className="customer-avatar">S</span><div><b>{data.customer.name}</b><small>Identified loyalty customer</small></div><strong>៛ {Number(latest.amount).toLocaleString()}</strong></div><div className="payment-meta"><span>Reference</span><b>{latest.reference ?? latest.id}</b><span>Payment state</span><b className="paid">● Paid</b><span>Customer value</span><a href={data.customer.wallet_url}>Open wallet →</a></div><a className="receipt-link" href={latest.receipt_url}>View hosted receipt →</a></> : <div className="empty-payment">Run the mobile demo payment to populate this merchant view.</div>}</article><article className="loyalty-card-merchant"><div className="section-label">LOYALTY OUTCOME</div><span>✦</span><h2>Payment turned into a return visit.</h2><p>The customer earned points automatically and can now redeem an offer in their PayKH wallet.</p><div><b>{data.customer.points_balance.toLocaleString()}</b><small>current points balance</small></div></article></section><section className="campaign-card"><div><p>CAMPAIGN SIGNAL</p><h2>Double points Friday</h2><span>Use the merchant dashboard to turn this test pattern into a scheduled campaign.</span></div><div className="campaign-flow"><b>KHQR paid</b><i>→</i><b>Points awarded</b><i>→</i><b>Voucher issued</b></div></section><footer>Isolated PayKH demo data · Test mode only · No money moved</footer></section></main>;
}
function Metric({ icon, label, value, detail }: { icon: string; label: string; value: string; detail: string }) { return <article><span>{icon}</span><p>{label}</p><b>{value}</b><small>{detail}</small></article> }
