'use client';

import { useState } from 'react';
import './wallet.css';

type View = 'home' | 'scan' | 'confirm' | 'success' | 'rewards' | 'pass' | 'merchant' | 'profile';
const vouchers = [{ title: 'Iced latte on us', code: 'PKH-CAFE-7W2', status: 'Ready' }];

export default function PaykhMobileDemo() {
  const [view, setView] = useState<View>('home');
  const [points, setPoints] = useState(2480);
  const [voucher, setVoucher] = useState(vouchers[0]);
  const [dark, setDark] = useState(false);
  const [earned, setEarned] = useState(false);
  const pay = () => { setPoints(p => p + 125); setEarned(true); setView('success'); };
  const redeem = () => { setVoucher({ title: '15% off your next order', code: 'PKH-SAVE-4J8', status: 'Ready' }); setPoints(p => p - 500); setView('pass'); };

  return <main className={dark ? 'paykh-demo dark' : 'paykh-demo'}>
    <div className="demo-stage"><aside className="demo-brief"><div className="demo-brand"><i>◆</i> PayKH <span>Interactive demo</span></div><p>MERCHANT PAYMENT + LOYALTY</p><h1>One journey.<br />More reasons<br />to return.</h1><div className="demo-flow"><b>1</b><span>Discover</span><i /> <b>2</b><span>Pay with KHQR</span><i /> <b>3</b><span>Earn & redeem</span></div><div className="demo-scope"><strong>What this demonstrates</strong><span>KHQR checkout</span><span>Loyalty points & tiers</span><span>Rewards & vouchers</span><span>Scratch cards & referral</span><span>Merchant campaign insight</span></div></aside>
      <section className="demo-phone" aria-label="PayKH mobile product demo"><div className="device-status"><b>9:41</b><i /><span>▮▮▮ ᴡɪꜰɪ ▰</span></div><div className="demo-app">
        {view === 'home' && <Home points={points} earned={earned} go={setView} />}
        {view === 'scan' && <Scan back={() => setView('home')} next={() => setView('confirm')} />}
        {view === 'confirm' && <Confirm back={() => setView('scan')} pay={pay} />}
        {view === 'success' && <Success points={points} go={setView} />}
        {view === 'rewards' && <Rewards points={points} redeem={redeem} go={setView} />}
        {view === 'pass' && <Pass points={points} voucher={voucher} go={setView} />}
        {view === 'merchant' && <Merchant back={() => setView('home')} />}
        {view === 'profile' && <Profile dark={dark} setDark={setDark} />}
      </div>{!['scan', 'confirm', 'success', 'merchant'].includes(view) && <Nav view={view} go={setView} />}</section></div>
  </main>;
}

function Home({ points, earned, go }: { points:number; earned:boolean; go:(v:View)=>void }) { return <><header className="app-top"><div className="logo"><i>◆</i> PayKH</div><button aria-label="Notifications">♢<em /></button></header><div className="demo-label">DEMO EXPERIENCE</div><section className="hello"><p>Good morning, Serey</p><h1>Your rewards, ready to go.</h1></section><button className="loyalty-card" onClick={() => go('pass')}><div><span>MALIS COFFEE</span><b>{points.toLocaleString()} <small>points</small></b><p>Gold member · 520 points to next reward</p></div><i>✦</i><strong>View my pass →</strong></button>{earned && <div className="earned-toast"><span>✓</span><div><b>Points added</b><small>+125 from your Malis Coffee payment</small></div><button onClick={() => go('pass')}>View</button></div>}<section className="action-grid"><button onClick={() => go('scan')}><span>⌁</span><b>Pay</b><small>Scan a KHQR</small></button><button onClick={() => go('pass')}><span>▦</span><b>My pass</b><small>Rewards & vouchers</small></button><button onClick={() => go('rewards')}><span>✦</span><b>Rewards</b><small>Use your points</small></button></section><section className="section-block"><div className="section-head"><h2>For you</h2><button onClick={() => go('rewards')}>See rewards</button></div><button className="offer-card" onClick={() => go('rewards')}><span>2×</span><div><b>Double points Friday</b><small>Earn more at selected coffee partners</small></div><i>›</i></button></section><section className="section-block"><div className="section-head"><h2>Explore nearby</h2><button onClick={() => go('merchant')}>View all</button></div><button className="nearby-card" onClick={() => go('merchant')}><span className="store-avatar">M</span><div><b>Malis Coffee · BKK1</b><small>0.4 km · KHQR & rewards available</small></div><i>›</i></button></section></> }
function Scan({ back, next }: { back:()=>void; next:()=>void }) { return <div className="pay-screen"><header><button onClick={back} aria-label="Back">‹</button><b>Pay with KHQR</b><button aria-label="Help">?</button></header><p>Align the merchant KHQR in the frame</p><div className="scan-frame"><i /><i /><i /><i /><em /></div><section className="scan-detected"><span className="store-avatar">M</span><div><b>Malis Coffee · BKK1</b><small>Verified PayKH merchant</small></div><button onClick={next}>Continue</button></section><div className="scan-actions"><button><span>▧</span>Upload QR</button><button><span>⌕</span>Find merchant</button><button><span>?</span>Need help</button></div></div> }
function Confirm({ back, pay }: { back:()=>void; pay:()=>void }) { return <div className="confirm-screen"><header><button onClick={back}>‹</button><b>Confirm payment</b><span /></header><span className="store-avatar large">M</span><h1>Malis Coffee</h1><p className="verified">✓ Verified PayKH merchant</p><div className="amount">៛ 12,500</div><p className="usd">≈ $3.05 · KHQR payment</p><div className="payment-note"><span>ⓘ</span><p>You’ll complete this payment in your linked KHQR app. PayKH will add your loyalty points after confirmation.</p></div><div className="payment-detail"><span>Merchant</span><b>Malis Coffee · BKK1</b><span>Reference</span><b>PKH-DEMO-1042</b></div><button className="primary" onClick={pay}>Confirm demo payment <i>→</i></button><small className="demo-safe">Demo only · no money will move</small></div> }
function Success({ points, go }: { points:number; go:(v:View)=>void }) { return <div className="success-screen"><div className="success-mark">✓</div><p>PAYMENT CONFIRMED</p><h1>៛ 12,500</h1><span>Paid to Malis Coffee</span><section><div><b>+125</b><small>points earned</small></div><i /><div><b>{points.toLocaleString()}</b><small>points balance</small></div></section><div className="receipt-line"><span>Receipt</span><b>PKH-DEMO-1042</b><span>Time</span><b>Today · 10:42</b></div><button className="primary" onClick={() => go('pass')}>View my updated pass <i>→</i></button><button className="text-button" onClick={() => go('home')}>Back to home</button></div> }
function Rewards({ points, redeem, go }: { points:number; redeem:()=>void; go:(v:View)=>void }) { const rewardList=[{title:'15% off your next order',desc:'Malis Coffee · valid for 14 days',cost:500,icon:'%'},{title:'Iced latte on us',desc:'Any Malis Coffee branch',cost:1200,icon:'☕'},{title:'Partner treat',desc:'New reward from a nearby merchant',cost:2500,icon:'✦'}];return <><header className="sub-top"><div><p>USE YOUR POINTS</p><h1>Rewards</h1></div><button onClick={()=>go('home')}>×</button></header><div className="points-strip"><span>Available now</span><b>{points.toLocaleString()} points</b></div><div className="rewards-stack">{rewardList.map((r,i)=><article key={r.title}><span className="reward-badge">{r.icon}</span><div><h2>{r.title}</h2><p>{r.desc}</p><b>{r.cost.toLocaleString()} points</b></div><button disabled={points<r.cost} onClick={i===0?redeem:undefined}>{points<r.cost?'More points':'Redeem'}</button></article>)}</div><section className="reward-info"><span>✦</span><div><b>Every payment gets you closer</b><p>Earn points when you pay a participating PayKH merchant.</p></div></section></> }
function Pass({ points, voucher, go }: { points:number; voucher:{title:string;code:string;status:string};go:(v:View)=>void }) { return <><header className="sub-top"><div><p>YOUR WALLET</p><h1>My pass</h1></div><button onClick={()=>go('home')}>×</button></header><section className="member-card"><div><span>MALIS COFFEE</span><b>Serey Chenda</b><small>Gold · PayKH rewards</small></div><strong>{points.toLocaleString()}<small> pts</small></strong><i>◆</i></section><section className="section-block"><div className="section-head"><h2>Ready to use</h2><span>1 active</span></div><article className="voucher"><span>✓</span><div><b>{voucher.title}</b><code>{voucher.code}</code><small>Show this at checkout</small></div><i>{voucher.status}</i></article></section><section className="section-block"><div className="section-head"><h2>Lucky draw</h2><span>1 to reveal</span></div><button className="scratch"><span>✦</span><div><b>Friday coffee surprise</b><small>Tap to reveal your reward</small></div><i>→</i></button></section><button className="invite"><span>♢</span><div><b>Invite friends, earn together</b><small>Your referral code: SEREY-24</small></div><i>→</i></button></> }
function Merchant({ back }: { back:()=>void }) { return <div className="merchant-page"><header><button onClick={back}>‹</button><b>Merchant details</b><button>♡</button></header><div className="merchant-hero"><span className="store-avatar xl">M</span><h1>Malis Coffee</h1><p>Specialty coffee · Phnom Penh</p><span>✓ Verified PayKH merchant</span></div><section className="merchant-stats"><div><b>2×</b><small>Friday points</small></div><div><b>0.4 km</b><small>from you</small></div><div><b>Open</b><small>until 9:00 PM</small></div></section><section className="merchant-offer"><p>ACTIVE OFFER</p><h2>Double points Friday</h2><span>Pay with KHQR to earn automatically</span></section><div className="merchant-list"><b>Accepted here</b><span>KHQR payment</span><span>PayKH rewards</span><span>Gift cards</span></div><button className="primary" onClick={back}>Scan to pay <i>⌁</i></button></div> }
function Profile({ dark, setDark }: { dark:boolean;setDark:(v:boolean)=>void }) { return <><header className="sub-top"><div><p>ACCOUNT</p><h1>Profile</h1></div></header><section className="profile-identity"><span>S</span><div><b>Serey Chenda</b><small>PayKH demo member</small></div><i>›</i></section><section className="settings-list"><p>PREFERENCES</p><button onClick={()=>setDark(!dark)}><span>◐</span><b>Dark mode</b><small>{dark?'On':'Off'}</small><i className={dark?'switch on':'switch'}><em /></i></button><button><span>◎</span><b>Language</b><small>English</small><i>›</i></button><p>SUPPORT</p><button><span>?</span><b>How PayKH works</b><small>Payment & reward guide</small><i>›</i></button><button><span>◇</span><b>Privacy & security</b><small>Your wallet data</small><i>›</i></button></section><p className="demo-foot">PayKH mobile demo · Cambodia first</p></> }
function Nav({ view, go }: {view:View;go:(v:View)=>void}) {return <nav className="demo-nav"><button className={view==='home'?'active':''} onClick={()=>go('home')}><span>⌂</span>Home</button><button className={view==='rewards'?'active':''} onClick={()=>go('rewards')}><span>✦</span>Rewards</button><button className={view==='pass'?'active':''} onClick={()=>go('pass')}><span>▦</span>My pass</button><button className={view==='profile'?'active':''} onClick={()=>go('profile')}><span>◉</span>Profile</button></nav>}
