'use client';

import { useEffect, useState } from 'react';
import './wallet.css';
import './figma-entry.css';
import './figma-reference.css';

type View = 'home' | 'scan' | 'confirm' | 'success' | 'rewards' | 'pass' | 'merchant' | 'profile';
type Entry = 'onboarding' | 'signin' | 'app';
const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL ?? 'http://localhost:4000';
const vouchers = [{ title: 'Iced latte on us', code: 'PKH-CAFE-7W2', status: 'Ready' }];

export default function PaykhMobileDemo() {
  const [view, setView] = useState<View>('home');
  const [entry, setEntry] = useState<Entry>('onboarding');
  const [points, setPoints] = useState(2480);
  const [voucher, setVoucher] = useState(vouchers[0]);
  const [dark, setDark] = useState(false);
  const [earned, setEarned] = useState(false);
  const [customerId, setCustomerId] = useState('');
  const [rewardId, setRewardId] = useState('');
  const [walletUrl, setWalletUrl] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const apply = (data: any) => { setCustomerId(data.customer_id); setWalletUrl(data.wallet_url); setPoints(data.wallet?.points_balance ?? points); setRewardId(data.wallet?.rewards?.[0]?.id ?? ''); };
  useEffect(() => { fetch(`${API_BASE}/demo/mobile`).then(r => r.ok ? r.json() : Promise.reject()).then(apply).catch(() => setError('Demo service unavailable.')); }, []);
  const pay = async () => { setBusy(true); setError(''); try { const r = await fetch(`${API_BASE}/demo/mobile/pay`, { method: 'POST' }); if (!r.ok) throw new Error(); apply(await r.json()); setEarned(true); setView('success'); } catch { setError('Could not complete the demo payment.'); } finally { setBusy(false); } };
  const redeem = async () => { if (!customerId || !rewardId) return setError('Demo wallet is loading.'); setBusy(true); setError(''); try { const r = await fetch(`${API_BASE}/wallet/${customerId}/redeem`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ reward_id: rewardId }) }); const data = await r.json(); if (!r.ok) throw new Error(data.message); setVoucher({ title: '15% off your next order', code: data.code, status: 'Ready' }); apply(await fetch(`${API_BASE}/demo/mobile`).then(x => x.json())); setView('pass'); } catch (e) { setError(e instanceof Error ? e.message : 'Could not redeem this reward.'); } finally { setBusy(false); } };

  return <main className={`${dark ? 'paykh-demo dark' : 'paykh-demo'}${entry !== 'app' ? ' figma-reference-mode' : ''}`}>
    <div className="demo-stage"><aside className="demo-brief"><div className="demo-brand"><i>◆</i> PayKH <span>Interactive demo</span></div><p>MERCHANT PAYMENT + LOYALTY</p><h1>One journey.<br />More reasons<br />to return.</h1><div className="demo-flow"><b>1</b><span>Discover</span><i /> <b>2</b><span>Pay with KHQR</span><i /> <b>3</b><span>Earn & redeem</span></div><div className="demo-scope"><strong>What this demonstrates</strong><span>KHQR checkout</span><span>Loyalty points & tiers</span><span>Rewards & vouchers</span><span>Scratch cards & referral</span><span>Merchant campaign insight</span></div></aside>
      <section className="demo-phone" aria-label="PayKH mobile product demo"><div className="device-status"><b>9:41</b><i /><span>▮▮▮ ᴡɪꜰɪ ▰</span></div>{entry !== 'app' ? <EntryFlow entry={entry} setEntry={setEntry} /> : <><div className="demo-app">
        {error && <button className="demo-error" onClick={() => setError('')}>{error}<b>×</b></button>}
        {view === 'home' && <Home points={points} earned={earned} go={setView} />}
        {view === 'scan' && <Scan back={() => setView('home')} next={() => setView('confirm')} />}
        {view === 'confirm' && <Confirm back={() => setView('scan')} pay={pay} busy={busy} />}
        {view === 'success' && <Success points={points} go={setView} walletUrl={walletUrl} />}
        {view === 'rewards' && <Rewards points={points} redeem={redeem} go={setView} busy={busy} />}
        {view === 'pass' && <Pass points={points} voucher={voucher} go={setView} walletUrl={walletUrl} />}
        {view === 'merchant' && <Merchant back={() => setView('home')} />}
        {view === 'profile' && <Profile dark={dark} setDark={setDark} />}
      </div>{!['scan', 'confirm', 'success', 'merchant'].includes(view) && <Nav view={view} go={setView} />}</>}</section></div>
  </main>;
}

function EntryFlow({ entry, setEntry }: { entry: Entry; setEntry: (entry: Entry) => void }) {
  const [slide, setSlide] = useState(0);
  const slides = [
    { tone: 'blue', visual: <div className="money-float"><b>៛ 12,500</b><span>Payment confirmed</span><small>MC · Malis Coffee</small></div>, title: "Cambodia's KHQR Wallet", body: 'Pay with KHQR at participating merchants and collect PayKH rewards in seconds.' },
    { tone: 'green', visual: <div className="khqr-art"><i>▪▪▪</i><i>▪ ▪</i><i>▪▪▪</i><b>KHQR</b></div>, title: 'Scan Any KHQR Code', body: "Pay at merchants across Cambodia with KHQR — the National Bank's certified payment standard." },
    { tone: 'blue', visual: <div className="wheel-art"><b>+500 pts</b><i>✦</i><span>Try again</span><span>Gift</span></div>, title: 'Earn Rewards Every Day', body: 'Collect points on every transaction. Unlock scratch cards and Cambodian merchant deals.' },
  ];
  if (entry === 'signin') return <div className="figma-signin"><div className="signin-hero"><div className="signin-logo">P<em>•</em></div><h1>PayKH</h1><p>Welcome back</p></div><section><h2>Sign In</h2><p>Enter your phone number to continue</p><label>PHONE NUMBER<div><span>🇰🇭 +855</span><input aria-label="Phone number" placeholder="12 345 678" inputMode="tel" /></div></label><button className="bio" onClick={() => setEntry('app')}><span>◉</span><div><b>Face ID / Fingerprint</b><small>Quick biometric login</small></div><i>›</i></button><button className="signin-continue" onClick={() => setEntry('app')}>Continue</button><div className="or"><i />or<i /></div><button className="create-account" onClick={() => setEntry('app')}>Create New Account</button></section></div>;
  const item = slides[slide];
  return <div className={`figma-onboarding ${item.tone}`}><button className="skip" onClick={() => setEntry('signin')}>Skip</button><div className="onboarding-visual">{item.visual}</div><section><h1>{item.title}</h1><p>{item.body}</p><div className="intro-bottom"><div className="dots">{slides.map((_, i) => <i className={i === slide ? 'on' : ''} key={i} />)}</div><button onClick={() => slide < slides.length - 1 ? setSlide(slide + 1) : setEntry('signin')}>{slide === slides.length - 1 ? 'Get Started' : 'Next'} <b>→</b></button></div></section></div>;
}

function Home({ points, earned, go }: { points:number; earned:boolean; go:(v:View)=>void }) { return <><header className="app-top"><div className="logo"><i>◆</i> PayKH</div><button aria-label="Notifications">♢<em /></button></header><div className="demo-label">DEMO EXPERIENCE</div><section className="hello"><p>Good morning, Serey</p><h1>Your rewards, ready to go.</h1></section><button className="loyalty-card" onClick={() => go('pass')}><div><span>MALIS COFFEE</span><b>{points.toLocaleString()} <small>points</small></b><p>Gold member · 520 points to next reward</p></div><i>✦</i><strong>View my pass →</strong></button>{earned && <div className="earned-toast"><span>✓</span><div><b>Points added</b><small>+125 from your Malis Coffee payment</small></div><button onClick={() => go('pass')}>View</button></div>}<section className="action-grid"><button onClick={() => go('scan')}><span>⌁</span><b>Pay</b><small>Scan a KHQR</small></button><button onClick={() => go('pass')}><span>▦</span><b>My pass</b><small>Rewards & vouchers</small></button><button onClick={() => go('rewards')}><span>✦</span><b>Rewards</b><small>Use your points</small></button></section><section className="section-block"><div className="section-head"><h2>For you</h2><button onClick={() => go('rewards')}>See rewards</button></div><button className="offer-card" onClick={() => go('rewards')}><span>2×</span><div><b>Double points Friday</b><small>Earn more at selected coffee partners</small></div><i>›</i></button></section><section className="section-block"><div className="section-head"><h2>Explore nearby</h2><button onClick={() => go('merchant')}>View all</button></div><button className="nearby-card" onClick={() => go('merchant')}><span className="store-avatar">M</span><div><b>Malis Coffee · BKK1</b><small>0.4 km · KHQR & rewards available</small></div><i>›</i></button></section></> }
function Scan({ back, next }: { back:()=>void; next:()=>void }) { return <div className="pay-screen"><header><button onClick={back} aria-label="Back">‹</button><b>Pay with KHQR</b><button aria-label="Help">?</button></header><p>Align the merchant KHQR in the frame</p><div className="scan-frame"><i /><i /><i /><i /><em /></div><section className="scan-detected"><span className="store-avatar">M</span><div><b>Malis Coffee · BKK1</b><small>Verified PayKH merchant</small></div><button onClick={next}>Continue</button></section><div className="scan-actions"><button><span>▧</span>Upload QR</button><button><span>⌕</span>Find merchant</button><button><span>?</span>Need help</button></div></div> }
function Confirm({ back, pay, busy }: { back:()=>void; pay:()=>void; busy:boolean }) { return <div className="confirm-screen"><header><button onClick={back}>‹</button><b>Confirm payment</b><span /></header><span className="store-avatar large">M</span><h1>Malis Coffee</h1><p className="verified">✓ Verified PayKH merchant</p><div className="amount">៛ 12,500</div><p className="usd">≈ $3.05 · KHQR payment</p><div className="payment-note"><span>ⓘ</span><p>This test-mode checkout runs through PayKH’s payment, loyalty, reward and ledger flow. No money will move.</p></div><div className="payment-detail"><span>Merchant</span><b>Malis Coffee · BKK1</b><span>Reference</span><b>PKH-DEMO-1042</b></div><button className="primary" disabled={busy} onClick={pay}>{busy ? 'Confirming…' : 'Confirm demo payment'} <i>→</i></button><small className="demo-safe">Demo only · no money will move</small></div> }
function Success({ points, go, walletUrl }: { points:number; go:(v:View)=>void; walletUrl:string }) { return <div className="success-screen"><div className="success-mark">✓</div><p>PAYMENT CONFIRMED</p><h1>៛ 12,500</h1><span>Paid to Malis Coffee</span><section><div><b>+125</b><small>points earned</small></div><i /><div><b>{points.toLocaleString()}</b><small>points balance</small></div></section><div className="receipt-line"><span>Receipt</span><b>PKH-DEMO-1042</b><span>Time</span><b>Just now</b></div><button className="primary" onClick={() => go('pass')}>View my updated pass <i>→</i></button>{walletUrl && <a className="text-button" href={walletUrl}>Open API-backed wallet</a>}<button className="text-button" onClick={() => go('home')}>Back to home</button></div> }
function Rewards({ points, redeem, go, busy }: { points:number; redeem:()=>void; go:(v:View)=>void; busy:boolean }) { const rewardList=[{title:'15% off your next order',desc:'Malis Coffee · valid for 14 days',cost:500,icon:'%'},{title:'Iced latte on us',desc:'Any Malis Coffee branch',cost:1200,icon:'☕'},{title:'Partner treat',desc:'New reward from a nearby merchant',cost:2500,icon:'✦'}];return <><header className="sub-top"><div><p>USE YOUR POINTS</p><h1>Rewards</h1></div><button onClick={()=>go('home')}>×</button></header><div className="points-strip"><span>Available now</span><b>{points.toLocaleString()} points</b></div><div className="rewards-stack">{rewardList.map((r,i)=><article key={r.title}><span className="reward-badge">{r.icon}</span><div><h2>{r.title}</h2><p>{r.desc}</p><b>{r.cost.toLocaleString()} points</b></div><button disabled={points<r.cost || busy} onClick={i===0?redeem:undefined}>{busy&&i===0?'…':points<r.cost?'More points':'Redeem'}</button></article>)}</div><section className="reward-info"><span>✦</span><div><b>Every payment gets you closer</b><p>Earn points when you pay a participating PayKH merchant.</p></div></section></> }
function Pass({ points, voucher, go, walletUrl }: { points:number; voucher:{title:string;code:string;status:string};go:(v:View)=>void; walletUrl:string }) { return <><header className="sub-top"><div><p>YOUR WALLET</p><h1>My pass</h1></div><button onClick={()=>go('home')}>×</button></header><section className="member-card"><div><span>MALIS COFFEE</span><b>Serey Chenda</b><small>Gold · PayKH rewards</small></div><strong>{points.toLocaleString()}<small> pts</small></strong><i>◆</i></section><section className="section-block"><div className="section-head"><h2>Ready to use</h2><span>1 active</span></div><article className="voucher"><span>✓</span><div><b>{voucher.title}</b><code>{voucher.code}</code><small>Show this at checkout</small></div><i>{voucher.status}</i></article></section><section className="section-block"><div className="section-head"><h2>Lucky draw</h2><span>1 to reveal</span></div><button className="scratch"><span>✦</span><div><b>Friday coffee surprise</b><small>Tap to reveal your reward</small></div><i>→</i></button></section><button className="invite"><span>♢</span><div><b>Invite friends, earn together</b><small>Your referral code: SEREY-24</small></div><i>→</i></button>{walletUrl && <a className="wallet-link" href={walletUrl}>Open complete customer wallet →</a>}</> }
function Merchant({ back }: { back:()=>void }) { return <div className="merchant-page"><header><button onClick={back}>‹</button><b>Merchant details</b><button>♡</button></header><div className="merchant-hero"><span className="store-avatar xl">M</span><h1>Malis Coffee</h1><p>Specialty coffee · Phnom Penh</p><span>✓ Verified PayKH merchant</span></div><section className="merchant-stats"><div><b>2×</b><small>Friday points</small></div><div><b>0.4 km</b><small>from you</small></div><div><b>Open</b><small>until 9:00 PM</small></div></section><section className="merchant-offer"><p>ACTIVE OFFER</p><h2>Double points Friday</h2><span>Pay with KHQR to earn automatically</span></section><div className="merchant-list"><b>Accepted here</b><span>KHQR payment</span><span>PayKH rewards</span><span>Gift cards</span></div><button className="primary" onClick={back}>Scan to pay <i>⌁</i></button></div> }
function Profile({ dark, setDark }: { dark:boolean;setDark:(v:boolean)=>void }) { return <><header className="sub-top"><div><p>ACCOUNT</p><h1>Profile</h1></div></header><section className="profile-identity"><span>S</span><div><b>Serey Chenda</b><small>PayKH demo member</small></div><i>›</i></section><section className="settings-list"><p>PREFERENCES</p><button onClick={()=>setDark(!dark)}><span>◐</span><b>Dark mode</b><small>{dark?'On':'Off'}</small><i className={dark?'switch on':'switch'}><em /></i></button><button><span>◎</span><b>Language</b><small>English</small><i>›</i></button><p>SUPPORT</p><button><span>?</span><b>How PayKH works</b><small>Payment & reward guide</small><i>›</i></button><button><span>◇</span><b>Privacy & security</b><small>Your wallet data</small><i>›</i></button></section><p className="demo-foot">PayKH mobile demo · Cambodia first</p></> }
function Nav({ view, go }: {view:View;go:(v:View)=>void}) {return <nav className="demo-nav"><button className={view==='home'?'active':''} onClick={()=>go('home')}><span>⌂</span>Home</button><button className={view==='rewards'?'active':''} onClick={()=>go('rewards')}><span>✦</span>Rewards</button><button className={view==='pass'?'active':''} onClick={()=>go('pass')}><span>▦</span>My pass</button><button className={view==='profile'?'active':''} onClick={()=>go('profile')}><span>◉</span>Profile</button></nav>}
